# create your drupal and postgres config here, based off the last assignment
version: '2'

services: 
  drupal:
    build: .
    image: custom-drupal
    ports:
      - "8080:80"
    volumes: 
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
  

  psql:
    image: postgres
    volumes:
      - drupal-data:/var/lib/postgresql/data
    environment:
      - POSTGRESS_PASSWORD=banana

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data:

    